modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/DyeMobDye/issues"
license="MIT"

[[mods]]
modId="dyemobdye"
version="${file.jarVersion}"
displayName="Dye Mob Dye"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dye-mob-dye"
authors="Mrbysco"
description='''
DYE MOB DYEEEEEE!
'''
[[dependencies.dyemobdye]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"