modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/DyeMobDye/issues"
license="MIT"

[[mods]]
modId="dyemobdye"
version="${file.jarVersion}"
displayName="Dye Mob Dye"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dye-mob-dye"
authors="Mrbysco"
description='''
DYE MOB DYEEEEEE!
'''
[[dependencies.dyemobdye]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.dyemobdye]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="dyemobdye.mixins.json"